spring.datasource:
  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  # url: jdbc:h2:./camunda-h2-default/process-engine;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa
#  url: jdbc:postgresql://localhost/postgres
#  username: postgres
#  password: postgres
spring.h2.console.enabled: true
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo

  filter:
    create: All tasks
server.port: 8081
